CREATE EXTERNAL TABLE ORDERS (
  O_ORDERKEY INT PRIMARY KEY, -- 1,500,000 entries
  O_CUSTKEY INT FOREIGN KEY,
  O_ORDERSTATUS STRING,
  O_ORDERPRICE FLOAT,
  O_TOTALPRICE FLOAT,
  O_ORDERDATE DATE,
  O_ORDERPRIORITY STRING,
  O_CLERK STRING,
  O_SHIPPRIORITY INT,
  O_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';