CREATE EXTERNAL TABLE LINEITEM (
  L_ORDERKEY INT FOREIGN KEY,
  L_PARTKEY INT FOREIGN KEY,
  L_SUPPKEY INT FOREIGN KEY,
  L_LINENUMBER INT,
  L_QUANTITY FLOAT,
  L_EXTENDEDpRICE FLOAT,
  L_DISCOUNT FLOAT,
  L_TAX FLOAT,
  L_RETURNFLAG STRING,
  L_LINESTATUS STRING,
  L_SHIPDATE DATE,
  L_COMMITDATE DATE,
  L_RECEIPTDATE DATE,
  L_SHIPINSTRUCT STRING,
  L_SHIPMODE STRING,
  L_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';