CREATE EXTERNAL TABLE PART (
  P_PARTKEY INT PRIMARY KEY, -- 200,000 entries
  P_NAME STRING,
  P_MFGR STRING,
  P_BRAND STRING,
  P_TYPE STRING,
  P_SIZE INT,
  P_CONTAINER STRING,
  P_RETAILPRICE FLOAT,
  P_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';