CREATE EXTERNAL TABLE NATION (
  N_NATIONKEY INT PRIMARY KEY,
  N_NAME STRING,
  N_REGIONKEY INT FOREIGN KEY,
  N_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';