CREATE EXTERNAL TABLE PARTSUP (
  PS_PARTKEY INT FOREIGN KEY,
  PS_SUPPKEY INT FOREIGN KEY,
  PS_AVAILQTY INT,
  PS_SUPPLYCOST FLOAT,
  PS_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';