CREATE EXTERNAL TABLE SUPPLIER (
  S_SUPKEY INT PRIMARY KEY, -- 10,000 entries
  S_NAME STRING,
  S_ADDRESS STRING,
  S_NATIONKEY INT FOREIGN KEY,
  S_PHONE STRING,
  S_ACCTBAL FLOAT,
  S_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';