CREATE EXTERNAL TABLE CUSTOMER (
  C_CUSTKEY INT PRIMARY KEY, -- 150,000 entries
  C_NAME STRING,
  C_ADDRESS STRING,
  C_NATIONKEY INT FOREIGN KEY,
  C_PHONE STRING,
  C_ACCTBAL FLOAT,
  C_MKTSEGMENT STRING,
  C_COMMENT STRING,
)
STORED AS PARQUET
LOCATION 's3://your-bucket-name/path-to-parquet-files/';